#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.appli_ne.mirror                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/ic_launcher.png                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Mirror                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Easy to use mirror application! Zoom, exposure, lighting and freeze functions.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : appli-ne                                
your_link                                 :                      
your_city                                 : Japan                                
email_address                             : info.appline.jp@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : appli-ne
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Pause preview
    description                           : Pause preview to see image.
    fontawesome_icon_name                 : pause-circle
    
  - title                                 : Resume preview
    description                           : Resume preview and show image.
    fontawesome_icon_name                 : play-circle

  - title                                 : Zoom
    description                           : You can zoom the image up to 10 times.
    fontawesome_icon_name                 : search-plus

  - title                                 : Exposure adjustment
    description                           : You can adjust the exposure (brightness).
    fontawesome_icon_name                 : adjust

  - title                                 : Light frame
    description                           : It can be used in dark places with light frames.
    fontawesome_icon_name                 : lightbulb
  
  - title                                 : Gallery
    description                           : You can check the images in the gallery.
    fontawesome_icon_name                 : file-image

  - title                                 : Saving still images
    description                           : Save the still image.
    fontawesome_icon_name                 : save

  - title                                 : Sharing still image
    description                           : Share a still image.
    fontawesome_icon_name                 : share-alt

  - title                                 : 
    description                           : 
    fontawesome_icon_name                 : 

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
